import turtle
turtle.color("green")
turtle.speed(25)

turtle.begin_fill()
turtle.forward(350)
turtle.left(180)
turtle.forward(710)
turtle.left(90)
turtle.forward(330)
turtle.left(90)
turtle.forward(715)
turtle.left(90)
turtle.forward(330)
turtle.end_fill()

bread = turtle.Turtle()
bread.color("saddle brown")

bread.begin_fill()
bread.left(180)
bread.forward(150)
bread.right(90)
bread.forward(200)
bread.right(90)
bread.forward(180)
bread.right(90)
bread.forward(200)
bread.right(90)
bread.forward(40)
bread.end_fill()

sam = turtle.Turtle()
sam.color("red")

sam.penup()
sam.left(180)
sam.forward(90)
sam.pendown()
sam.begin_fill()
sam.right(90)
sam.forward(70)
sam.right(90)
sam.forward(50)
sam.right(90)
sam.forward(70)
sam.right(90)
sam.forward(50)
sam.end_fill()

tim = turtle.Turtle()
tim.color("black")

tim.penup()
tim.left(180)
tim.forward(45)
tim.right(90)
tim.forward(30)
tim.pendown()
tim.begin_fill()
tim.circle(6)
tim.end_fill()

flash = turtle.Turtle()
flash.color("dim gray")

flash.penup()
flash.left(90)
flash.forward(200)
flash.pendown()
flash.right(90)
flash.forward(30)
flash.begin_fill()
flash.left(180)
flash.forward(180)
flash.right(120)
flash.forward(160)
flash.right(114)
flash.forward(170)
flash.end_fill()

tye = turtle.Turtle()
tye.color("deep sky blue")

tye.penup()
tye.left(180)
tye.forward(30)
tye.right(90)
tye.forward(110)
tye.pendown()
tye.begin_fill()
tye.right(90)
tye.forward(40)
tye.left(90)
tye.forward(40)
tye.left(90)
tye.forward(40)
tye.left(90)
tye.forward(40)
tye.end_fill()
tye.penup()
tye.right(90)
tye.forward(60)
tye.pendown()
tye.begin_fill()
tye.right(90)
tye.forward(40)
tye.left(90)
tye.forward(40)
tye.left(90)
tye.forward(40)
tye.left(90)
tye.forward(40)
tye.end_fill()

will = turtle.Turtle()
will.color("black")

will.penup()
will.left(180)
will.forward(15)
will.right(90)
will.forward(110)
will.pendown()
will.begin_fill()
will.forward(40)
will.right(90)
will.forward(9)
will.right(90)
will.forward(40)
will.right(90)
will.forward(9)
will.end_fill()

bill = turtle.Turtle()
bill.color("black")

bill.penup()
bill.left(180)
bill.forward(30)
bill.right(90)
bill.forward(123)
bill.pendown()
bill.begin_fill()
bill.right(90)
bill.forward(40)
bill.left(90)
bill.forward(9)
bill.left(90)
bill.forward(40)
bill.left(90)
bill.forward(9)
bill.end_fill()

leo = turtle.Turtle()
leo.color("black")

leo.penup()
leo.left(180)
leo.forward(105)
leo.right(90)
leo.forward(110)
leo.pendown()
leo.begin_fill()
leo.forward(40)
leo.left(90)
leo.forward(9)
leo.left(90)
leo.forward(40)
leo.left(90)
leo.forward(9)
leo.end_fill()

eve = turtle.Turtle()
eve.color("black")

eve.penup()
eve.left(180)
eve.forward(130)
eve.right(90)
eve.forward(123)
eve.pendown()
eve.begin_fill()
eve.right(90)
eve.forward(40)
eve.left(90)
eve.forward(9)
eve.left(90)
eve.forward(40)
eve.left(90)
eve.forward(9)
eve.end_fill()

sal = turtle.Turtle()
sal.color("yellow")

sal.penup()
sal.left(180)
sal.forward(250)
sal.right(90)
sal.forward(300)
sal.pendown()
sal.begin_fill()
sal.circle(100)
sal.end_fill()

murr = turtle.Turtle()
murr.color("sienna")
murr.penup()
murr.forward(200)
murr.left(90)
murr.pendown()
murr.begin_fill()
murr.forward(100)
murr.right(90)
murr.forward(15)
murr.right(90)
murr.forward(100)
murr.right(90)
murr.forward(15)
murr.end_fill()

joe = turtle.Turtle()
joe.color("green")

joe.penup()
joe.forward(260)
joe.left(90)
joe.forward(150)
joe.pendown()
joe.begin_fill()
joe.circle(50)
joe.end_fill()

turtle.exitonclick()